### ISSUE TITLE
different prefix: "" and "/Users/user/rails_project"

### ISSUE THREAD

**Issue by kntmrkm** [r7kamura/view_source_map#15]
```
ArgumentError (different prefix: "" and "/Users/user/rails_project"):
```

`letter_opener_web`というgemのＶiewを見る時に発生します。

同じように`view_source_map`を入れているプロジェクトで発生しないものもあるので、
`view_source_map`に関連するかわからないですが、issue立てさせていただきました。

同じようなissueが以下になります。
- https://github.com/CocoaPods/CocoaPods/issues/5541
- https://github.com/CocoaPods/CocoaPods/pull/5550/files#diff-9c3ade95b9c6b6efe38348516dac9b2dR188

<img width="839" alt="letteropenerweb" src="https://cloud.githubusercontent.com/assets/2703486/23578371/8a4426ae-0118-11e7-9a84-3f6498b34d73.png">

**Comment by r7kamura** [comment]
https://docs.ruby-lang.org/ja/latest/class/Pathname.html#I_RELATIVE_PATH_FROM を見ると、

> self が相対パスなら base_directory も相対パス、self が絶対パスなら base_directory も絶対パスでなければなりません。

と書いていますね。これに違反した場合、同様のエラーが表示されることが分かります。

```bash
$ ruby -rpathname -e 'Pathname.new(".").relative_path_from(Pathname.new("/"))'
/Users/r7kamura/.rbenv/versions/2.2.3/lib/ruby/2.2.0/pathname.rb:508:in `relative_path_from': different prefix: "" and "/" (ArgumentError)
        from -e:1:in `<main>'
```

貼っていただいてる画像のエラーのスタックトレースの2つ目に表示されている

https://github.com/r7kamura/view_source_map/blob/d50a94dc776081aadce7cd72afd3e346ba5b3ff6/lib/view_source_map.rb#L45

を見ると以下のようなコードがあります。

```ruby
path = Pathname.new(template.identifier)
name = path.relative_path_from(Rails.root)
```

Rails.root は絶対パスを返すので、template.identifier も同様に絶対パスでないといけないが、この場合そうなってはいないのでエラーが出ているのかもしれないと考えています。

この場合、エラーメッセージを見るに `template.identifier` が空文字列である場合を考慮していないのが原因で、これが空文字列の場合 view_source_map でコメントを挿入しても意味を為さないので、`template.identifier.to_s.empty?` の場合は無視するようなコードに変えれば改善しそうですね。

**Comment by r7kamura** [comment]
https://github.com/r7kamura/view_source_map/pull/16 で対処してみました。

**Comment by kntmrkm** [comment]
https://github.com/r7kamura/view_source_map/pull/17
