### ISSUE TITLE
Support layout files

### ISSUE THREAD

**Issue by Samemura** [r7kamura/view_source_map#22]
こちらのGemでは、layoutファイルの内容はコメント出力されないでしょうか？？
layoutファイルも一緒に見れると嬉しいです。layoutファイルの中でpartialをレンダリングする場合は特に助かりますm(_ _)m

**Comment by r7kamura** [comment]
残念ながら、現在のところ layout は対応していません。あえて対応していないという訳ではなく、単純に当時実装するのが大変そうだったというだけなので、もし対応する Pull Request をいただければ喜んで merge したいと思っています。

**Comment by Samemura** [comment]
ありがとうございます。すぐに対応できなさそうなので、クローズしますm(_ _)m

**Comment by r7kamura** [comment]
🙏
